#!/bin/bash

set -e -u

cat > /tmp/payload <&0

echo "#!/bin/bash" > /tmp/script.sh
jq -r '.source.check_script // ""' < /tmp/payload >> /tmp/script.sh
chmod +x /tmp/script.sh
cat /tmp/payload | /tmp/script.sh
